### PR TITLE
Working on plugins [Still don't merge]

### PR DESCRIPTION
**Pull request by testeddoughnut**

### CODE REVIEW

**Comment by testeddoughnut** [comment]
@cryptk The javascript tests are still angry. Will leave that chicken to you.

**Comment by cryptk** [comment]
@testeddoughnut do we want to tag 0.1 before or after this work go's in?

**Comment by testeddoughnut** [comment]
@cryptk before, please tag it in its current state.

**Comment by cryptk** [comment]
Cool, I'll get it tagged for 0.1 tomorrow

**Comment by testeddoughnut** [comment]
@cryptk I think this is about ready to merge. Still needs work tying all of the backend work into the frontend. As of right now the plugin system works for registering scheduler tasks, registering blueprints, registering `opsy` sub-commands, and registering objects to include in the shell context when generating an ipython shell. The front-end is going to be completely broken until plugin support is added. This will likely require a new `register_links` method or something like that on the BaseOpsyPlugin class.

**Comment by cryptk** [comment]
Cool, I'll check it out tomorrow after my internet is fixed.

**Comment by testeddoughnut** [comment]
Went ahead and merged this. Front-end in dev is now officially broken again =D

**Pull request merged**
